# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='existdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docindex', models.IntegerField(default=-1)),
                ('raw_path', models.CharField(max_length=200)),
                ('result_path', models.CharField(max_length=200)),
            ],
        ),
    ]
